apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-ssd-client-provisioner
  labels:
    app: nfs-ssd-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: nfs-storage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-ssd-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-ssd-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: ssd-nfs-provisioner
            - name: NFS_SERVER
              value: 192.168.4.30
            - name: NFS_PATH
              value: /export/ssd-storage
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.4.30
            path: /export/ssd-storage
